on:
  push:
    tags: ["*"]

env:
  PDF_RELEASE_NAME: Suchomelova_cv.pdf

name: Create Release
jobs:
  call-pdf-build:
    uses: ./.github/workflows/build.yml

  build:
    name: Create Release
    needs: ["call-pdf-build"]
    runs-on: ubuntu-latest
    steps:
      - name: Download pdf-build artifact
        uses: actions/download-artifact@v3
        with:
          name: suchomelova_cv
          path: pdf/
      - run: mv pdf/suchomelova_cv.pdf ${{env.PDF_RELEASE_NAME}}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          name:
          files: |
            ${{env.PDF_RELEASE_NAME}}
